### ISSUE TITLE
Desktop download links fail

### ISSUE THREAD

**Issue by garywill** [tango-adb/bridge-rs#1]
These 2 links fail to download :
https://app.tangoapp.dev/desktop
https://app.tangoapp.dev/desktop-files/0.1.0/linux/x86-64/tango-bridge (downloads an HTML file)

**Comment by yume-chan** [comment]
Thanks for reporting!

I double-checked the link [app.tangoapp.dev/desktop](https://app.tangoapp.dev/desktop) is correct. If you see 404 on it, you might be on an old version and need to update. This is because the whole app is cached locally and offline first.

I found a configuration error causing the link [app.tangoapp.dev/desktop-files/0.1.0/linux/x86-64/tango-bridge](https://app.tangoapp.dev/desktop-files/0.1.0/linux/x86-64/tango-bridge) to show 404 when opened directly. It will be fixed in next version. But it should still work if you click the link on the download page, or use command line tools like curl or wget to download it.

**Comment by yume-chan** [comment]
> I found a configuration error causing the link [app.tangoapp.dev/desktop-files/0.1.0/linux/x86-64/tango-bridge](https://app.tangoapp.dev/desktop-files/0.1.0/linux/x86-64/tango-bridge) to show 404 when opened directly

It should now work in version 1.8.3
